"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { api } from "@/lib/api";
import type { CurrentLocation, Tracking } from "@/lib/types";
import { MapView } from "./MapView";

export function LiveLocationPanel({ tripId, isDriver }: { tripId: number; isDriver: boolean }) {
  const { token } = useAuth(); const [tracking, setTracking] = useState<Tracking | null>(null); const [location, setLocation] = useState<CurrentLocation | null>(null); const [status, setStatus] = useState("desconectado"); const [permission, setPermission] = useState("sin solicitar"); const [error, setError] = useState("");
  const socket = useRef<WebSocket | null>(null); const watch = useRef<number | null>(null); const lastSent = useRef(0); const reconnect = useRef<number | null>(null); const mounted = useRef(true); const connectRef = useRef<() => Promise<void>>(async () => undefined);
  const stopWatch = useCallback(() => { if (watch.current !== null) { navigator.geolocation.clearWatch(watch.current); watch.current = null; } }, []);
  const connect = useCallback(async () => {
    if (!token || !mounted.current || socket.current?.readyState === WebSocket.OPEN || socket.current?.readyState === WebSocket.CONNECTING) return;
    setStatus("reconectando");
    try { const connection = await api.locationWebSocketUrl(tripId, token); const ws = new WebSocket(connection.url); socket.current = ws;
      ws.onmessage = (raw) => { const event = JSON.parse(raw.data) as { type: string; data: CurrentLocation }; if (event.type === "connected") setStatus("conectado"); if (event.type === "location.updated") setLocation(event.data); if (event.type === "tracking.finished") { setStatus("finalizado"); stopWatch(); } };
      ws.onclose = () => { if (socket.current === ws) socket.current = null; if (mounted.current) { setStatus("reconectando"); reconnect.current = window.setTimeout(() => { void api.currentLocation(tripId, token).then(setLocation).catch(() => undefined); void connectRef.current(); }, 2500); } }; ws.onerror = () => ws.close();
    } catch { if (mounted.current) reconnect.current = window.setTimeout(() => void connectRef.current(), 3000); }
  }, [stopWatch, token, tripId]);
  async function beginSharing() { if (!token || watch.current !== null) return; if (!navigator.geolocation) { setError("Este dispositivo no ofrece geolocalización."); return; } setTracking(await api.shareLocation(tripId, true, token)); watch.current = navigator.geolocation.watchPosition((position) => { setPermission("concedido"); const now = Date.now(); if (now - lastSent.current < 4000) return; lastSent.current = now; const payload = { latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, speed: position.coords.speed, heading: position.coords.heading, client_timestamp: new Date(position.timestamp).toISOString() }; setLocation({ ...payload, updated_at: new Date().toISOString(), stale: false }); if (socket.current?.readyState === WebSocket.OPEN) socket.current.send(JSON.stringify({ type: "location.update", data: payload })); else void api.sendLocation(tripId, payload, token).catch(() => setError("No se pudo enviar la ubicación.")); }, (geoError) => { setPermission("denegado"); setError(geoError.message); }, { enableHighAccuracy: true, timeout: 12000, maximumAge: 3000 }); }
  useEffect(() => { mounted.current = true; connectRef.current = connect; if (token) { api.tracking(tripId, token).then(setTracking).catch(() => undefined); api.currentLocation(tripId, token).then(setLocation).catch(() => undefined); void connect(); } return () => { mounted.current = false; socket.current?.close(); stopWatch(); if (reconnect.current) window.clearTimeout(reconnect.current); }; }, [connect, stopWatch, token, tripId]);
  async function start() { if (token) setTracking(await api.startTracking(tripId, token)); } async function pause() { if (token) { stopWatch(); setTracking(await api.pauseTracking(tripId, token)); } } async function resume() { if (token) setTracking(await api.resumeTracking(tripId, token)); } async function finish() { if (token && window.confirm("¿Finalizar el viaje y detener la ubicación?")) { stopWatch(); setTracking(await api.finishTracking(tripId, token)); } }
  return <section className="mobility-panel live-location"><header><div><p className="eyebrow">Ubicación en tiempo real</p><h2 className="text-xl font-black">{location ? location.stale ? "Ubicación desactualizada" : "Conductor en movimiento" : "Aún sin ubicación"}</h2></div><span className={status === "conectado" ? "badge-active" : "badge-pending"}>{status}</span></header><MapView className="live-map" markers={location ? [{ id: "driver", latitude: location.latitude, longitude: location.longitude, color: "#047857", label: "Conductor" }] : []} />{location && <div className="location-meta"><span>Precisión: {Math.round(location.accuracy)} m</span><span>Actualizada: {new Date(location.updated_at).toLocaleTimeString()}</span></div>}{!location && <p className="map-help">El conductor debe iniciar el viaje y consentir compartir su ubicación.</p>}{error && <p className="error-message">{error}</p>}{isDriver && <div className="tracking-controls"><span>Permiso: {permission}</span>{!tracking && <button className="button-primary" type="button" onClick={start}>Iniciar viaje</button>}{tracking?.estado === "activo" && !tracking.compartir_ubicacion && <button className="button-primary" type="button" onClick={beginSharing}>Compartir ubicación</button>}{tracking?.estado === "activo" && <button className="button-secondary" type="button" onClick={pause}>Pausar</button>}{tracking?.estado === "pausado" && <button className="button-primary" type="button" onClick={resume}>Reanudar</button>}{tracking && ["activo", "pausado"].includes(tracking.estado) && <button className="button-danger" type="button" onClick={finish}>Finalizar</button>}</div>}</section>;
}
