"""initial migration

Revision ID: 95aa48282bc9
Revises: 
Create Date: 2025-04-22 10:34:34.386780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95aa48282bc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('contraseña', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('destino', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('asientos_disponibles', sa.Integer(), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=True),
    sa.Column('cancelado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viajes_id'), 'viajes', ['id'], unique=False)
    op.create_table('pasajeros_viajes',
    sa.Column('viaje_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pasajeros_viajes')
    op.drop_index(op.f('ix_viajes_id'), table_name='viajes')
    op.drop_table('viajes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
