"""add descripcion to viajes

Revision ID: a015d1f49f4a
Revises: 95aa48282bc9
Create Date: 2025-04-22 10:40:49.729202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a015d1f49f4a'
down_revision: Union[str, None] = '95aa48282bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viajes', sa.Column('descripcion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viajes', 'descripcion')
    # ### end Alembic commands ###
